### ISSUE TITLE
polygons that cross the bbox multiple times return joined results

### ISSUE THREAD

**Issue by tcql** [mapbox/lineclip#1]
<img width="357" alt="screen shot 2015-09-17 at 6 05 36 pm" src="https://cloud.githubusercontent.com/assets/348805/9947252/bb04149a-5d66-11e5-9791-ef016ffd5087.png">

I would expect 2 triangles, but I get back a single polygon. Is this expected behavior with Sutherland-Hodgman?

https://gist.github.com/tcql/ab60a9fecd8e9691d0a7

**Comment by mourner** [comment]
Yes, this is expected behavior with Sutherland-Hodgeman. It produces degenerate edges. This is a price to pay for exceptional performance of the algorithm.

**Comment by tcql** [comment]
:+1: cool. Just making sure. I'll move ahead on pulling together `turf-clip`, then ;)

**Comment by mourner** [comment]
@tcql awesome, looking forward to it!

**Comment by Andi-Lo** [comment]
Hey there, I got the very same issue but actually can not find a library or another algorithm which does solve this issues problem.

Is there any solution for this problem available or do you @mourner or @tcql know of any?
I am currently on a project where we want to visualize ship routes. For doing that we want to clip a world map containing all coastlines by a bounding box (depending on the envelope of the route). When lineclip produces degenerate edges we really run in to trouble when we want to draw the clipped polygon to the html canvas. E.g. like this is the clipped output when it cuts the same polygon multiple times:

![image](https://cloud.githubusercontent.com/assets/7545568/21931017/671d3842-d999-11e6-8ada-caa3e58db454.png)

And when we want to draw it (iterating over all features of the featureCollection)

![image](https://cloud.githubusercontent.com/assets/7545568/21931039/8ddbdfb0-d999-11e6-8e54-b73494d65588.png)

Do you know any solution to this problem? We basically would need for each clipping a new feature should be created. Then we would know when we would need to "lift the pen and go to the new feature location and then start drawing again".

**Comment by mourner** [comment]
@Andi-Lo the picture look more like you're trying to clip a polygon with a polyline clipping algorithm. Are you using `lineclip.polygon`?

**Comment by Andi-Lo** [comment]
yes I'm using lineclip.polygon

This is my clipping function:
```javascript
let clipPolygon = function(fc, bbox) {
  let points;
  let polygon;
  bbox = turf.size(turf.square(bbox), 2);
  let clipped = turf.featureCollection([]);
  turf.meta.featureEach(fc, function(feature) {
    points = turf.meta.coordAll(feature);
    if(points.length > 0)
      polygon = lineclip.polygon(points, bbox);
    if(polygon.length > 0)
      clipped.features.push(turf.lineString(polygon));
  });
  return clipped;
};
```
